import type { BrowserWindow, IpcMainEvent, Rectangle } from 'electron';
import type { VlcPlayerStrings } from '../i18n/types';
import type { VlcOverlayTrackItem, VlcPlaybackMode, VlcSetSourceOptions } from '../types';
import type { GraceController } from './grace';
import type { LayoutController } from './layout';
import type { OverlaySeekController } from './overlay/seek';
import type { OverlayWindowController } from './overlay/window';
import type { PlaylistController } from './playlist';
import type { SeekPreviewController } from './seek-preview-config';
import type { OverlayTrackCache } from './types';

/** Host surface exposed to vlc-player submodules via getters on VlcPlayer. */
export interface VlcPlayerHost {
  playerId: number;
  readonly destroyed: boolean;
  readonly window: BrowserWindow;
  source: string | null;
  containerSelector: string;
  readonly showControls: boolean;
  readonly showPageFullscreenButton: boolean;
  readonly autoAdvancePlaylist: boolean;
  readonly locale: string;
  readonly strings: VlcPlayerStrings;
  mediaToken: number;
  replayInProgress: boolean;
  mediaLabelParseForSource: string | null;
  embedPromise: Promise<void> | null;
  embedLayoutSynced: boolean;
  containerResizeObserverInstalled: boolean;
  lastPaintRaiseAt: number;

  readonly grace: GraceController;
  readonly seekPreview: SeekPreviewController;
  readonly playlist: PlaylistController;
  readonly layout: LayoutController;
  readonly overlayWindow: OverlayWindowController;
  readonly overlaySeek: OverlaySeekController;

  getState(): number;
  getLength(): number;
  getTime(): number;
  getPosition(): number;
  isPlaying(): boolean;
  isEmbedded(): boolean;
  getMute(): boolean;
  setMute(muted: boolean): void;
  toggleMute(): void;
  setRate(rate: number): void;
  getRate(): number;
  getFps(): number;
  setAudioTrack(id: number): void;
  setSubtitleTrack(id: number): void;
  getAudioTrack(): number;
  getSubtitleTrack(): number;
  getAudioTracks(): { id: number; name: string }[];
  getSubtitleTracks(): { id: number; name: string }[];
  getMediaInfo(): { parsed: boolean };
  getMediaMetadata(): { title?: string };
  getMediaTracksResult(): {
    data: Array<{ type: string; id: number; codec?: string; language?: string; description?: string }>;
  };
  parseMedia(options: { timeoutMs: number; maxWaitMs: number }): Promise<unknown>;
  addSubtitleFile(path: string): boolean;
  play(): void;
  togglePause(): void;
  setSource(src: string, options?: VlcSetSourceOptions): void;
  setSourceDirect(src: string, options?: VlcSetSourceOptions): void;
  emit(event: string, ...args: unknown[]): boolean;
  on(event: string, listener: (...args: unknown[]) => void): this;
  off(event: string, listener: (...args: unknown[]) => void): this;

  clampSeekTimeMs(ms: number): number;
  isMediaNaturallyComplete(): boolean;
  shouldReplayFromStart(): boolean;
  replayFromStart(): void;
  handlePlaybackEnd(): void;
  pushState(): void;
  pushStateProgress(): void;
  pushOverlayCachedState(playing: boolean): void;
  scheduleMediaLabelParse(): void;
  ensureOverlay(): void;
  scheduleLayoutSync(immediate?: boolean): void;
  hideOverlay(): void;
  showOverlay(): void;
  focusOverlay(options?: { stealWindowFocus?: boolean }): void;
  cancelOverlaySeekSession(): void;
  cancelSeekPreviewSprite(): void;
  resetOverlayStateCache(): void;
  markSourceChangeGrace(): void;
  markSeekGrace(): void;
  overlayIpcAllowed(event: IpcMainEvent): boolean;
  handleEscapeFullscreen(): void;
  togglePageFullscreen(): void;
  setFullScreen(on: boolean): Promise<void>;
  setPageFullscreen(on: boolean): Promise<void>;
  generateSeekPreviewSprite(): void;
  playPrevious(): boolean;
  playNext(): boolean;
  hasPlaylistControls(): boolean;
  hasPrevious(): boolean;
  hasNext(): boolean;
  isPageFullscreen(): boolean;
  isFullScreen(): boolean;
  getMediaDisplayLabel(): string;
  pickAndAddSubtitleFile(): Promise<void>;
  normalizeVolumeLevel(volume: number): number;
  syncOverlayMutedFromPlayer(): void;
  getOverlayTrackState(): OverlayTrackCache;
  raiseNativeLayer(): void;
  syncLayout(): void;
  createPlayerInstance(): void;
  attachOverlayStateEvents(): void;
  detachOverlayStateEvents(): void;
  unregisterIpc(): void;
  detachWindowListeners(): void;
  syncPlaybackEndListeners(): void;
  syncPlaylistIndexToSource(): void;
  getPlaybackMode(): VlcPlaybackMode;
  boundsNearlyEqual(a: Rectangle | null, b: Rectangle): boolean;
}
